[package]
name = "gorp_simple_miner"
version = "0.1.0"
authors = ["Jordan Grace <jordan.t.grace@gmail.com>"]
edition = "2018"

[dependencies]
gorp_blockchain = { git = "https://github.com/picklenerd/gorpcoin", branch = "main" }
